### ISSUE TITLE
Announce name of visitor via MQTT

### ISSUE THREAD

**Issue by mrosseel** [0x20/gatekeeper#3]
There should be an MQTT topic which announces the name of the person opening the gate. 
If the name is not known (this can happen during a social evening for instance) then some pre-agreed string can be used.

**Comment by qwaxys** [comment]
AFAIK the code should be in there but part of it has been commented out because it's untested.

**Comment by friedkiwi** [comment]
> AFAIK the code should be in there but part of it has been commented out because it's untested.

This was already implemented in my previous slew of fixes; I've just looked at it and I did the checks the wrong way around.

**Comment by friedkiwi** [comment]
Change deployed; will wait half an hour until it's after 6pm on the social to validate and then will cose the issue if fixed.

**Comment by friedkiwi** [comment]
Verified to be working, closing
