### ISSUE TITLE
get/set event mode + document

### ISSUE THREAD

**Issue by mrosseel** [0x20/gatekeeper#4]
It should be possible to:
* read an MQTT topic to know in which 'state' the gatekeeper is - such as 'normal', 'event', 'social', ...
* set the event state of gatekeeper by publishing a value to an MQTT topic

This interface should be shortly described in the readme, specifically the different possible states and their repercussions.

**Comment by friedkiwi** [comment]
Created a PR that adds this. It can currently only query event mode enabled or not because social is based on time.

**Comment by friedkiwi** [comment]
Merged and deployed, see README.md
